/** ~40 synthetic OEM support reports. Written like real field traffic. */
export const REPORTS = [
  {
    id: "R-001",
    date: "2026-08-12",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 86,
    source: "Fleet Ops",
    location: "Austin Depot",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Repeated campaign stalls across a commercial fleet and ops is already asking whether to pause rollout.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Techs cleared units by reflashing at the depot; remote retry did not finish the BCM step.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Failures cluster on units that sat unused overnight; same campaign completes on vehicles driven earlier.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Failure is during campaign 4.2.1 delivery to the BCM, not during normal door/lock operation.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "High-priority OTA reliability issue. Campaign 4.2.1 stalls on the BCM after overnight parking and currently needs depot reflash.",
    rawText:
      "fleet ops says update campaign 4.2.1 stalls around 60% on the body control module. only on units that were parked overnight. their tech cleared it by reflashing at the depot. third time this month, they are asking whether they should pause the campaign. no DTC stored on the ones we pulled logs from. seeing this across several vans at austin depot.",
  },
  {
    id: "R-002",
    date: "2026-08-13",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 120,
    source: "Depot Technician",
    location: "Rotterdam Hub",
    subsystem: "Body Control Module",
    severity: "P1",
    severityReason: "Three-digit unit count across a hub, same morning-after pattern, operational disruption for the fleet.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Units hung until a technician handled them on the lot; overnight remote retry did not recover them.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "All failed units had been sitting unused since the previous day; driven vehicles updated normally.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Campaign completes except on sleep-soaked vehicles during the BCM package, pointing at update resume after ECU sleep.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Same overnight OTA stall seen at a second depot. Driven vehicles are fine; parked units hang on BCM.",
    rawText:
      "three units failed their update first thing in the morning. all had been sitting unused since yesterday. campaign completed normally on vehicles driven earlier in the day, but overnight parked units are hanging during the BCM step. rotterdam hub, apex van, sw 4.2.1. we had to pull them into the bay. fleet ops wants a call-back today.",
  },
  {
    id: "R-003",
    date: "2026-08-14",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 14,
    source: "Dealer Tech",
    location: "Newark PDC",
    subsystem: "OTA Update",
    severity: "P2",
    severityReason: "Limited set of vehicles and a known ignition-cycle workaround exists, so impact is operational but contained.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Update finished after a manual ignition cycle; no depot reflash required on these units.",
    triggerCondition: "Ignition cycle during update",
    triggerReason: "Techs reproduced that cycling ignition unblocked the hung campaign.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Behavior is still campaign-state handling after a stall, not a BCM hardware fault.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Related OTA hang that recovered after ignition cycle. Smaller count, workaround exists, still same campaign family.",
    rawText:
      "tech confirmed campaign 4.2.1 sat at ~55% then finished after they did a key cycle. works after ignition cycle on 14 vans so far. started after campaign push last night. asking whether we should tell other depots to try that before they reflash. no DTC.",
  },
  {
    id: "R-004",
    date: "2026-08-15",
    vehicleModel: "Courier LCV",
    softwareVersion: "4.2.1",
    affectedVehicles: 47,
    source: "OEM Support",
    location: "Munich PDC",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Depot reflash required on dozens of commercial vehicles; campaign cannot be treated as self-healing.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Remote attempts exhausted; technician reflash at the depot was what actually cleared the ECU.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Same parked-overnight cohort as other 4.2.1 BCM stalls.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Update packaging/resume for BCM after sleep, not courier-specific hardware.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Courier LCV also needs depot reflash for the same overnight BCM stall on 4.2.1.",
    rawText:
      "customer reports OTA never finishes on the body controller. tech at munich pdc reflashed 47 couriers this week. vehicle was parked overnight every time. started after campaign 4.2.1. they are asking whether we should pause the campaign for LCV. came back on two units after a remote retry so they stopped relying on OTA.",
  },
  {
    id: "R-005",
    date: "2026-08-18",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 210,
    source: "Fleet Ops",
    location: "Chicago Central",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Large fleet impact plus an explicit request to halt the campaign; operational disruption is already material.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Field is not recovering remotely at this scale; they are routing vehicles through depots.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Ops correlated failures with vans that sat on the lot overnight before the window.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Campaign-level go/no-go decision sits with OTA platform plus field engineering support.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Fleet is asking to pause campaign 4.2.1 after overnight BCM stalls across 200+ vans.",
    rawText:
      "fleet ops says they are seeing this across several depots now. campaign 4.2.1 hanging on BCM after overnight sit. third week. they are asking whether they should pause the campaign nationally. we do not have a clean remote recovery. please advise before Friday push.",
  },
  {
    id: "R-006",
    date: "2026-08-19",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.2.1",
    affectedVehicles: 1,
    source: "Dealer Tech",
    location: "Scottsdale Store",
    subsystem: "OTA Update",
    severity: "P3",
    severityReason: "Single vehicle, not reproduced on other units at the store, no fleet signal in this ticket.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Store reflashed the one sedan; no indication remote tools were tried successfully.",
    triggerCondition: "Unclear",
    triggerReason: "Report does not say whether the car sat overnight, battery state, or network quality.",
    suggestedOwner: "Field Engineering",
    ownerReason: "Isolated dealer case — confirm it is not the overnight BCM pattern before escalating to OTA platform.",
    theme: "Isolated OTA Failures",
    triageSummary: "One sedan failed an update. No other vehicles involved. Treat as isolated unless more units appear.",
    rawText:
      "only one unit so far. helix sedan failed 4.2.1 in the service drive. tech reflashed it and sent the customer. we checked two other helix on the lot and they updated fine. no DTC stored. not sure what the car was doing overnight, customer just said it didn't finish.",
  },
  {
    id: "R-007",
    date: "2026-08-04",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.1.8",
    affectedVehicles: 1,
    source: "OEM Support",
    location: "Lab / Validation",
    subsystem: "Infotainment",
    severity: "P3",
    severityReason: "Single freeze during testing, recovered after reboot, no safety or fleet impact described.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Reboot restored the UI; no service parts or dealer visit required.",
    triggerCondition: "Unclear",
    triggerReason: "One occurrence in a test session; no ignition/charging/network context given.",
    suggestedOwner: "Infotainment",
    ownerReason: "Head-unit freeze is an IVI defect, not a vehicle immobilization event.",
    theme: "Infotainment Freeze (Isolated)",
    triageSummary: "One-off screen freeze in testing that recovered after reboot. Do not treat as critical.",
    rawText:
      "the screen froze once during testing. engineer rebooted the HU and it came back. only seen on this helix in the lab. no customer complaint. just logging it in case it shows up in the field.",
  },
  {
    id: "R-008",
    date: "2026-08-21",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 200,
    source: "Fleet Ops",
    location: "Dallas Metro",
    subsystem: "Infotainment",
    severity: "P1",
    severityReason: "Same freeze across ~200 fleet SUVs; drivers cannot use nav/media for stretches of the shift.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Reboot or ignition cycle restores the display; dealers are not replacing hardware at this volume.",
    triggerCondition: "Specific software version",
    triggerReason: "Started after 4.2.0 on Ridge SUV; older 4.1.x units in the same fleet are not reported.",
    suggestedOwner: "Infotainment",
    ownerReason: "Clustered HU freeze after a software drop, recoverable without a bay visit.",
    theme: "Infotainment Freeze After 4.2.0",
    triageSummary: "Fleet-wide Ridge SUV screen freeze after 4.2.0. High operational noise even though reboot recovers it.",
    rawText:
      "fleet ops says infotainment freeze is happening across about 200 ridge SUVs after 4.2.0. screen locks up mid-route, reboot clears it, then it comes back later in the day. seeing this across several depots in dallas. drivers are complaining they lose nav. not a one-off.",
  },
  {
    id: "R-009",
    date: "2026-08-08",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.1.8",
    affectedVehicles: 38,
    source: "Customer Care",
    location: "UK Retail",
    subsystem: "Infotainment",
    severity: "P2",
    severityReason: "Annoyance on a few dozen cars with a phone-reconnect workaround; not immobilizing.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Re-pairing or HU reboot restores Bluetooth; no technician parts involved.",
    triggerCondition: "Phone reconnect after Bluetooth drop",
    triggerReason: "Techs reproduced drop after the phone left and re-entered range.",
    suggestedOwner: "Infotainment",
    ownerReason: "BT stack on the head unit, not telematics backend.",
    theme: "Bluetooth Drops After Phone Reconnect",
    triageSummary: "Bluetooth drops after phone reconnect on Helix. Workaround exists; medium customer noise.",
    rawText:
      "customer reports bluetooth disconnects after the phone reconnects in the car. reproduced twice at the store. audio comes back if they forget the device and pair again. about 38 helix so far in UK retail. no DTC. started after 4.1.8 for some of them but not sure.",
  },
  {
    id: "R-010",
    date: "2026-08-09",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 22,
    source: "Dealer Tech",
    location: "Denver Store",
    subsystem: "Infotainment",
    severity: "P2",
    severityReason: "Nav map data looks stale for a small set; drivers still have a car that moves.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Map refresh / HU reset being used; no hardware swap yet.",
    triggerCondition: "Specific software version",
    triggerReason: "Appeared on 4.2.0 Ridge units; not reported on Apex in the same region.",
    suggestedOwner: "Infotainment",
    ownerReason: "On-board navigation freshness, not cellular modem.",
    theme: "Stale Navigation Map Data",
    triageSummary: "Navigation data looks stale on a small Ridge 4.2.0 population. Medium, recoverable remotely.",
    rawText:
      "nav not updating — still showing last week's road closure. tech confirmed HU clock is correct. only seen on ridge 4.2.0 here. 22 tickets. reboot does not always refresh the tiles. asking for a map package push.",
  },
  {
    id: "R-011",
    date: "2026-08-11",
    vehicleModel: "Apex Van",
    softwareVersion: "4.1.8",
    affectedVehicles: 95,
    source: "Fleet Ops",
    location: "Phoenix Desert Routes",
    subsystem: "Connectivity / Telematics",
    severity: "P1",
    severityReason: "Repeated cellular drops across almost 100 vans on active routes; live tracking and remote commands suffer.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Modem comes back on its own after several minutes; no bay visit unless it stays offline.",
    triggerCondition: "Poor cellular connectivity",
    triggerReason: "Ops tied drops to known weak-coverage desert corridors, not a single depot.",
    suggestedOwner: "Connectivity",
    ownerReason: "Telematics registration / modem recovery in poor RF, not BCM logic.",
    theme: "Intermittent Cellular / Telematics Drops",
    triageSummary: "Fleet vans dropping cellular on desert routes. High ops impact even though they reconnect.",
    rawText:
      "fleet ops says vans keep losing backend connection on the I-10 stretch. cellular drops repeatedly, telematics module reconnecting slowly, sometimes 8–10 minutes. seeing this across several depots feeding phoenix. 95 units this week. remote lock/unlock queued until they come back. not crashed, just offline.",
  },
  {
    id: "R-012",
    date: "2026-08-11",
    vehicleModel: "Courier LCV",
    softwareVersion: "4.1.8",
    affectedVehicles: 40,
    source: "OEM Support",
    location: "Phoenix Desert Routes",
    subsystem: "Connectivity / Telematics",
    severity: "P2",
    severityReason: "Same reconnect delay on a smaller courier set; annoying but they do return online.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Self-reconnect after minutes; no technician dispatch in this ticket.",
    triggerCondition: "Poor cellular connectivity",
    triggerReason: "Same corridor as the Apex cellular reports.",
    suggestedOwner: "Telematics",
    ownerReason: "Slow re-attach after loss of coverage is a telematics client issue.",
    theme: "Intermittent Cellular / Telematics Drops",
    triageSummary: "Couriers also take minutes to rejoin after cellular loss on the same routes.",
    rawText:
      "tech confirmed courier LCV telematics reconnects after several minutes once they leave the dead zone. delayed vehicle status in the fleet tool the whole time. 40 units. works after they hit better coverage. asking if we have a faster re-register.",
  },
  {
    id: "R-013",
    date: "2026-08-16",
    vehicleModel: "Volt Hatch",
    softwareVersion: "4.2.0",
    affectedVehicles: 31,
    source: "Dealer Tech",
    location: "Oslo Charge Hub",
    subsystem: "Charging",
    severity: "P1",
    severityReason: "Public charging sessions abort mid-charge on multiple EVs; drivers cannot complete a shift charge.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Handshake failures sometimes need a charge-port reset in the bay; unplug/replug is not enough for all.",
    triggerCondition: "Fast charging session",
    triggerReason: "Stops reported on DC fast posts, not overnight AC at home.",
    suggestedOwner: "Charging",
    ownerReason: "EVSE handshake / session teardown is charging stack ownership.",
    theme: "DC Charge Session Stops Unexpectedly",
    triageSummary: "DC sessions stopping mid-charge on Volt Hatch. Needs charging-stack attention; some bay resets.",
    rawText:
      "charging session stopping around 40–60% at the oslo hub. charger handshake problems on a couple of Alpitronic posts. 31 volt hatch. tech cleared two of them by resetting the charge ECU in the bay. came back after 4.2.0. fleet is asking whether they should avoid those posts.",
  },
  {
    id: "R-014",
    date: "2026-08-17",
    vehicleModel: "Volt Hatch",
    softwareVersion: "4.2.0",
    affectedVehicles: 18,
    source: "Customer Care",
    location: "Oslo Charge Hub",
    subsystem: "Charging",
    severity: "P2",
    severityReason: "Incorrect status after unplug is confusing but the vehicle is not stranded.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Status eventually corrects after ignition or app refresh; no parts.",
    triggerCondition: "End of charging session",
    triggerReason: "Stuck 'charging' after cable removed.",
    suggestedOwner: "Cloud Platform",
    ownerReason: "Vehicle is unplugged; cloud/app state is lagging the onboard session end.",
    theme: "Stale Charging Status After Unplug",
    triageSummary: "App/cluster still says charging after unplug. Medium UX issue, not a stranded vehicle.",
    rawText:
      "charging status remains charging after the vehicle is unplugged. customer reports they drove away and the app still showed charging for 20 min. 18 volt hatch. tech confirmed cable out, no current. no DTC stored.",
  },
  {
    id: "R-015",
    date: "2026-08-10",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 55,
    source: "Customer Care",
    location: "Seoul Metro",
    subsystem: "Mobile App",
    severity: "P2",
    severityReason: "Remote lock delayed but eventually lands; not a physical lock failure on the car.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Command succeeds late; no dealer visit required.",
    triggerCondition: "Backend command queue delay",
    triggerReason: "Cars online; delay is in command delivery, not sleep-wake in this set.",
    suggestedOwner: "Mobile App",
    ownerReason: "Remote command path from app through cloud; door ECU is locking when the command arrives.",
    theme: "Delayed Remote Lock Commands",
    triageSummary: "Remote lock delayed for Ridge owners. Function works late — cloud/app path, not BCM jam.",
    rawText:
      "remote lock command is delayed 30–90 seconds. customer reports they stood by the car waiting. 55 ridge suvs seoul. vehicle does lock, just late. connectivity looks fine in the live view. started after 4.2.0 for a subset.",
  },
  {
    id: "R-016",
    date: "2026-08-20",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 12,
    source: "Fleet Ops",
    location: "Austin Depot",
    subsystem: "Mobile App",
    severity: "P2",
    severityReason: "Small local count in this ticket; related large-fleet tickets should be joined on the theme.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Location catches up; no technician trip.",
    triggerCondition: "Delayed telematics location publish",
    triggerReason: "Vans move but the app pin lags.",
    suggestedOwner: "Cloud Platform",
    ownerReason: "Stale location is a status pipeline issue, not navigation maps.",
    theme: "Stale Vehicle Status in Mobile App",
    triageSummary: "A dozen vans showing stale location in the app. Join with the larger fleet-status theme.",
    rawText:
      "mobile app shows stale vehicle location, sometimes 15 minutes behind. fleet ops at austin, 12 vans. they still find the vans in the yard. asking if this is the same as the national status lag they heard about.",
  },
  {
    id: "R-017",
    date: "2026-08-22",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 28,
    source: "Dealer Tech",
    location: "Hamburg Workshop",
    subsystem: "Vehicle Gateway",
    severity: "P1",
    severityReason: "Gateway comms faults after the software drop interfere with diagnostics and some body traffic.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Tech had to reflash/reconfigure gateway; remote retry did not clear the bus errors.",
    triggerCondition: "Specific software version",
    triggerReason: "Started after campaign 4.2.1 on Apex; not seen on 4.1.8 remaining vans.",
    suggestedOwner: "Vehicle Software",
    ownerReason: "Gateway software interaction after the release, needs vehicle software plus diagnostics.",
    theme: "Gateway Faults After 4.2.1",
    triageSummary: "Gateway communication faults after 4.2.1 requiring workshop recovery. Possible regression.",
    rawText:
      "gateway communication fault after software update 4.2.1. U-codes on the bus, scan tool keeps dropping. 28 apex vans hamburg. tech confirmed came back after they reflashed the gateway. started after campaign. looks like a regression, we did not see this on 4.1.8.",
  },
  {
    id: "R-018",
    date: "2026-08-22",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 41,
    source: "Fleet Ops",
    location: "Hamburg Workshop",
    subsystem: "Body Control Module",
    severity: "P1",
    severityReason: "Door lock behavior wrong after update on a working fleet; security/ops concern though not a crash event.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "BCM config restore in the bay; remote lock still flaky until then.",
    triggerCondition: "Specific software version",
    triggerReason: "Began immediately after 4.2.1 BCM package.",
    suggestedOwner: "Body Electronics",
    ownerReason: "Lock logic lives on BCM; OTA may have delivered it but the defect is body electronics.",
    theme: "BCM Door-Lock Behavior After Update",
    triageSummary: "Door locks misbehave after 4.2.1 BCM update. Needs body electronics plus campaign review.",
    rawText:
      "BCM door-lock behavior after update — sliding door reports locked in the app but tech can open it with the handle. 41 vans. started after campaign 4.2.1. fleet is unhappy about yard security. no DTC stored on some, others have a body config checksum. cleared after BCM config reload at the workshop.",
  },
  {
    id: "R-019",
    date: "2026-08-07",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 16,
    source: "Dealer Tech",
    location: "Portland Store",
    subsystem: "Body Control Module",
    severity: "P2",
    severityReason: "Lighting config reset is annoying and needs a dealer setting restore, limited volume.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "DRL/welcome lighting required a configuration write; owners could not fix from the app.",
    triggerCondition: "Specific software version",
    triggerReason: "After 4.2.0 lighting profile reverted to factory.",
    suggestedOwner: "Body Electronics",
    ownerReason: "Lighting configuration domain on BCM.",
    theme: "Lighting Configuration Resets",
    triageSummary: "Lighting profiles reset after 4.2.0 on a small Ridge set. Dealer config write recovers it.",
    rawText:
      "lighting configuration resets after 4.2.0. welcome lights and DRL level gone. tech confirmed they had to rewrite the coding. 16 ridge. only seen on this model at portland. customers think it's a bug not a feature.",
  },
  {
    id: "R-020",
    date: "2026-08-05",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 6,
    source: "Fleet Manager",
    location: "Austin Depot",
    subsystem: "OTA Update",
    severity: "P3",
    severityReason: "Enhancement request for progress visibility; vehicles still update, this is not a failure report.",
    recoveryPath: "Unknown",
    recoveryReason: "No failure to recover — request is for better UI/telemetry.",
    triggerCondition: "Unclear",
    triggerReason: "Not an incident; no failure trigger.",
    suggestedOwner: "Product Management",
    ownerReason: "Feature ask for campaign progress, not a defect in an ECU.",
    theme: "Enhancement: OTA Progress Visibility",
    triageSummary: "Drivers/fleet want clearer OTA progress. Treat as P3 product request unless tied to the stall defects.",
    rawText:
      "drivers are asking if we can add a percent complete that doesn't jump backwards. fleet manager wants to see which ECU is installing. would be useful if the app showed more than just 'updating'. not a failed update, just complaining they cannot tell if it is stuck. 6 supervisors pinged us.",
  },
  {
    id: "R-021",
    date: "2026-08-06",
    vehicleModel: "Courier LCV",
    softwareVersion: "4.1.8",
    affectedVehicles: 4,
    source: "Fleet Manager",
    location: "Rotterdam Hub",
    subsystem: "OTA Update",
    severity: "P3",
    severityReason: "Scheduling preference, not a malfunction.",
    recoveryPath: "Unknown",
    recoveryReason: "No recovery action — enhancement.",
    triggerCondition: "Unclear",
    triggerReason: "Request, not a failure mode.",
    suggestedOwner: "Product Management",
    ownerReason: "OTA scheduling is a product capability ask.",
    theme: "Enhancement: Scheduled OTA Windows",
    triageSummary: "Fleet wants to schedule OTA windows. Enhancement, not an incident.",
    rawText:
      "fleet manager wants the ability to schedule updates after 21:00 local so vans are not flashing during loading. would be useful if we could stagger by depot. they are not reporting failures in this ticket, just the ask.",
  },
  {
    id: "R-022",
    date: "2026-08-06",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 8,
    source: "Fleet Ops",
    location: "Chicago Central",
    subsystem: "Cloud Backend",
    severity: "P3",
    severityReason: "Request for better fleet-level alerts; current tickets still arrive by email/phone.",
    recoveryPath: "Unknown",
    recoveryReason: "No vehicle fault in this report.",
    triggerCondition: "Unclear",
    triggerReason: "Process/tooling request.",
    suggestedOwner: "Product Management",
    ownerReason: "Alerting product, not a vehicle ECU bug.",
    theme: "Enhancement: Fleet-Level Alerts",
    triageSummary: "Ops wants fleet-level alerts instead of one-off emails. P3 tooling/product request.",
    rawText:
      "fleet ops says would be useful if we got one alert when 10+ vans share the same OTA error instead of 10 emails. they are asking for fleet-level alerts. enhancement, they know. still drowning in tickets this month.",
  },
  {
    id: "R-023",
    date: "2026-08-07",
    vehicleModel: "Volt Hatch",
    softwareVersion: "4.2.0",
    affectedVehicles: 5,
    source: "Fleet Manager",
    location: "Oslo Charge Hub",
    subsystem: "Charging",
    severity: "P3",
    severityReason: "Ask for richer charging telemetry, not a session abort.",
    recoveryPath: "Unknown",
    recoveryReason: "No failure described.",
    triggerCondition: "Unclear",
    triggerReason: "Feature request.",
    suggestedOwner: "Product Management",
    ownerReason: "Charging status UX/product.",
    theme: "Enhancement: Detailed Charging Status",
    triageSummary: "More detailed charging status requested. Enhancement unless tied to the DC abort theme.",
    rawText:
      "would be useful if charging status showed kW, remaining minutes, and which fault if handshake fails. fleet manager in oslo. not saying the car failed today, just the app is too vague when something goes wrong.",
  },
  {
    id: "R-024",
    date: "2026-08-23",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.1",
    affectedVehicles: 73,
    source: "Depot Technician",
    location: "Toronto Yard",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Same overnight stall pattern on another model, dozens of units, depot time burning.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Yard team is flashing BCM on the lot; OTA retry not trusted.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Morning-after failures on units that were not driven.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Campaign 4.2.1 BCM step after sleep, now also on Ridge.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Ridge SUVs hanging on the same overnight BCM update. Different wording, same campaign defect.",
    rawText:
      "campaign completed normally on vehicles driven earlier in the day, but overnight parked units are hanging during the BCM step. toronto yard, ridge suv 4.2.1. we are treating it like a sleep/resume bug. 73 this week. please do not tell us to 'just retry OTA' — already did.",
  },
  {
    id: "R-025",
    date: "2026-08-24",
    vehicleModel: "Apex Van",
    softwareVersion: "4.1.8",
    affectedVehicles: 64,
    source: "Fleet Ops",
    location: "Andalusia Routes",
    subsystem: "Connectivity / Telematics",
    severity: "P1",
    severityReason: "Same cellular drop pattern in another region, material fleet tracking gap.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Reconnects when coverage returns; no workshop.",
    triggerCondition: "Poor cellular connectivity",
    triggerReason: "Rural coverage holes, same symptom as Phoenix tickets.",
    suggestedOwner: "Connectivity",
    ownerReason: "Modem/back-end attach behavior under weak RF.",
    theme: "Intermittent Cellular / Telematics Drops",
    triageSummary: "Same telematics drop, southern Spain routes. Regional duplicate of the Phoenix connectivity theme.",
    rawText:
      "same connectivity issue but from another region — vans in andalusia dropping off the map for 5–12 min. fleet ops says it looks identical to the phoenix tickets. 64 apex. telematics module reconnecting slowly. not asking for a tow, asking for a modem fix.",
  },
  {
    id: "R-026",
    date: "2026-08-03",
    vehicleModel: "Volt Hatch",
    softwareVersion: "4.2.0",
    affectedVehicles: 1,
    source: "Customer Care",
    location: "Home charger — Portland",
    subsystem: "Charging",
    severity: "P3",
    severityReason: "Language sounds like immobilization but the car finished a normal charge and was parked; no fault.",
    recoveryPath: "Unknown",
    recoveryReason: "Nothing to recover — session ended normally.",
    triggerCondition: "End of charging session",
    triggerReason: "Charge completed; vehicle was stationary as expected.",
    suggestedOwner: "Diagnostics",
    ownerReason: "Needs a careful read of logs so scary wording does not page the wrong on-call.",
    theme: "Harmless Charge-Complete Misread",
    triageSummary: "Scary wording, not a stranded vehicle. Charge completed normally; car was parked on purpose.",
    rawText:
      "URGENT — vehicle completely stopped in the driveway, customer panicked, said it would not go. tech confirmed SOC 100%, charging session had ended normally, they just had not pressed start. no DTC. cable was already unplugged. please do not escalate as immobilization. one unit so far.",
  },
  {
    id: "R-027",
    date: "2026-08-25",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 640,
    source: "Fleet Ops",
    location: "National (multi-depot)",
    subsystem: "Mobile App",
    severity: "P2",
    severityReason: "Each ticket looks minor (stale status) but the same behavior is on hundreds of vans — large operational drag.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Status eventually refreshes; nobody is towing vans for this.",
    triggerCondition: "Cloud status pipeline lag",
    triggerReason: "App/backend showing old SOC/location while CAN data on the vehicle is current.",
    suggestedOwner: "Cloud Platform",
    ownerReason: "Scale of stale telemetry is a cloud ingest/cache problem.",
    theme: "Stale Vehicle Status in Mobile App",
    triageSummary: "Looks like a small app glitch; 640 vans nationally with stale status. Should rank high on Themes.",
    rawText:
      "one vehicle occasionally shows stale status in the app — that is how dispatchers phrase it. looking at the fleet tool though we are seeing the same lag across hundreds of vans (we counted 640 this morning). SOC and location behind by 10–20 min. vehicles are fine. this is becoming how people dispatch. please do not close as 'single unit'.",
  },
  {
    id: "R-028",
    date: "2026-08-02",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.1.8",
    affectedVehicles: 1,
    source: "Dealer Tech",
    location: "Miami Store",
    subsystem: "Infotainment",
    severity: "P2",
    severityReason: "Single hardware failure, customer impacted until replaced, not a software campaign.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Display unit replaced; software reflash did not help.",
    triggerCondition: "Hardware fault",
    triggerReason: "Tech found a cracked LVDS cable / water in the HU — not reproducible in software.",
    suggestedOwner: "Field Engineering",
    ownerReason: "One-off hardware; do not cluster with the 4.2.0 freeze campaign.",
    theme: "One-off Hardware Display Fault",
    triageSummary: "Physical HU/cable damage on one sedan. Do not treat as the fleet freeze theme.",
    rawText:
      "screen black. looked like the freeze tickets at first. tech confirmed water ingress and a chewed LVDS cable (rodent). only one unit so far. reflashed twice, no change, replaced the display. hardware. closing against software once parts landed.",
  },
  {
    id: "R-029",
    date: "2026-08-26",
    vehicleModel: "Courier LCV",
    softwareVersion: "5.0.1-beta",
    affectedVehicles: 88,
    source: "OEM Support",
    location: "Beta fleet — Stuttgart",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Version-specific failure on the beta branch affecting most of a pilot fleet.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Rolling back to 4.2.1 remotely recovered units; no reflash for most.",
    triggerCondition: "Specific software version",
    triggerReason: "Only 5.0.1-beta; 4.2.1 controls in the same depot are fine.",
    suggestedOwner: "Vehicle Software",
    ownerReason: "Beta image defect; software release engineering.",
    theme: "5.0.1-beta Version-Specific OTA Defect",
    triageSummary: "Pilot 5.0.1-beta fails where 4.2.1 succeeds. Rollback works. Version-specific, not overnight-sleep.",
    rawText:
      "started after campaign 5.0.1-beta. OTA aborts at package verify. only seen on courier LCV in the stuttgart pilot. 88 of 100. 4.2.1 vans next to them are fine. we rolled most back remotely. asking to halt 5.0.1. not the overnight BCM thing — different log signature.",
  },
  {
    id: "R-030",
    date: "2026-08-01",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.1.8",
    affectedVehicles: 3,
    source: "Customer Care",
    location: "Boston Store",
    subsystem: "Infotainment",
    severity: "P3",
    severityReason: "Few cars, reboot clears it, no repeat storm.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Ignition/HU reboot is sufficient.",
    triggerCondition: "Unclear",
    triggerReason: "Owners did not capture what they were doing; no logs attached.",
    suggestedOwner: "Infotainment",
    ownerReason: "Soft UI hang.",
    theme: "Infotainment Freeze (Isolated)",
    triageSummary: "Three sedans, reboot fixes the HU. Low severity until it clusters.",
    rawText:
      "problem that disappears after reboot. audio UI stuck. three helix. customer reports they were parked. no logs. works after ignition cycle. only these three so far.",
  },
  {
    id: "R-031",
    date: "2026-08-27",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 19,
    source: "Dealer Tech",
    location: "Atlanta Store",
    subsystem: "Vehicle Gateway",
    severity: "P1",
    severityReason: "Requires a technician with a factory tool; customers cannot self-recover.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Gateway secure access + config — not doable from the app.",
    triggerCondition: "Specific ECU configuration",
    triggerReason: "Mis-matched gateway dataset after a partial update.",
    suggestedOwner: "Diagnostics",
    ownerReason: "Needs diagnostic procedure and correct dataset, then vehicle software follow-up.",
    theme: "Gateway Faults After 4.2.1",
    triageSummary: "Partial update left gateway config wrong. Technician-only recovery on 19 Ridge units.",
    rawText:
      "problem that requires technician intervention. gateway in limp after a partial 4.2.0->4.2.1 attempt. scan tool needed. 19 ridge atlanta. remote did nothing. tech has a workaround: load dataset D-17 then retry. please publish that.",
  },
  {
    id: "R-032",
    date: "2026-08-12",
    vehicleModel: "Apex Van",
    softwareVersion: "4.1.8",
    affectedVehicles: 27,
    source: "OEM Support",
    location: "Remote ops",
    subsystem: "Connectivity / Telematics",
    severity: "P2",
    severityReason: "Recovered remotely; moderate count; no yard visit.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "Wake + telematics reset from backend restored connectivity.",
    triggerCondition: "Vehicle entering sleep mode",
    triggerReason: "Deep sleep then slow to take a network wake.",
    suggestedOwner: "Telematics",
    ownerReason: "Remote wake/re-register path worked — keep it with telematics.",
    theme: "Intermittent Cellular / Telematics Drops",
    triageSummary: "Sleep-wake telematics lag recovered remotely. Same connectivity family, milder.",
    rawText:
      "problem recoverable remotely. vans not showing online after weekend sit. we sent a telematics reset from the backend and they came back. 27 apex. no depot. looking like sleep mode then slow PDP. not the desert coverage tickets but related enough.",
  },
  {
    id: "R-033",
    date: "2026-08-14",
    vehicleModel: "Ridge SUV",
    softwareVersion: "4.2.0",
    affectedVehicles: 8,
    source: "OEM Support",
    location: "Unknown / mixed",
    subsystem: "Powertrain",
    severity: "P2",
    severityReason: "Mild driveability comment, small n, cannot reproduce; not safety-documented.",
    recoveryPath: "Unknown",
    recoveryReason: "No clear recovery because the trigger is not identified.",
    triggerCondition: "Unclear",
    triggerReason: "Missing conditions, logs, and whether it was after charge, OTA, or cold start.",
    suggestedOwner: "Diagnostics",
    ownerReason: "Need a proper snapshot before assigning powertrain vs gateway.",
    theme: "Incomplete / Unclear Field Reports",
    triageSummary: "Possible hesitation, trigger unknown. Do not over-classify; collect evidence.",
    rawText:
      "customer reports a hesitation once. maybe powertrain? tech could not reproduce. 8 ridge from different stores dumped into one email. no DTC, no speed, no ambient temp, no whether they had just updated. unclear trigger. we need more.",
  },
  {
    id: "R-034",
    date: "2026-08-14",
    vehicleModel: "Unknown",
    softwareVersion: "Unknown",
    affectedVehicles: 1,
    source: "Customer Care",
    location: "Not provided",
    subsystem: "Cloud Backend",
    severity: "P3",
    severityReason: "Incomplete ticket; cannot evidence fleet, safety, or even the model.",
    recoveryPath: "Unknown",
    recoveryReason: "Insufficient information to recommend a path.",
    triggerCondition: "Unclear",
    triggerReason: "Model, SW, VIN, and symptom details are missing.",
    suggestedOwner: "Field Engineering",
    ownerReason: "First job is to complete the report, not to guess an ECU owner.",
    theme: "Incomplete / Unclear Field Reports",
    triageSummary: "Incomplete report. Do not invent severity. Bounce for VIN, model, and logs.",
    rawText:
      "car acting weird after the thing. customer hung up. no VIN, no model, no software version, no location. please advise??",
  },
  {
    id: "R-035",
    date: "2026-08-19",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 11,
    source: "Depot Technician",
    location: "Austin Depot",
    subsystem: "OTA Update",
    severity: "P2",
    severityReason: "Useful workaround documented; small extra count on top of the main OTA theme.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Workaround still needs a tech on site (keep-awake + retry), but avoids full reflash.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Same overnight BCM stall; workaround is keep module awake.",
    suggestedOwner: "Field Engineering",
    ownerReason: "Capture and publish the workaround while OTA platform fixes resume.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Tech workaround: keep-awake then retry. Still the overnight OTA theme, slightly easier recovery.",
    rawText:
      "tech confirmed a workaround: plug in a keep-awake, don't let BCM sleep, then retry campaign 4.2.1. avoided full reflash on 11 vans. still takes a person at the depot. sharing in case it helps other yards. vehicle was parked overnight as usual.",
  },
  {
    id: "R-036",
    date: "2026-08-28",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.2.1",
    affectedVehicles: 52,
    source: "OEM Support",
    location: "QA + Field",
    subsystem: "Infotainment",
    severity: "P1",
    severityReason: "New after 4.2.1 on Helix — looks like a regression, 50+ field units plus QA.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "HU reset remotely helps; investigating a follow-up OTA.",
    triggerCondition: "Specific software version",
    triggerReason: "Not present on 4.1.8 Helix; appeared the week 4.2.1 landed.",
    suggestedOwner: "Infotainment",
    ownerReason: "Release regression on IVI.",
    theme: "Infotainment Freeze After 4.2.0",
    triageSummary: "Helix 4.2.1 may have brought the freeze to another model. Treat as regression, high.",
    rawText:
      "report that suggests a possible regression after a release. helix 4.2.1 now showing the same HU freeze we had on ridge 4.2.0. 52 cars plus two QA benches. 4.1.8 helix next to them are clean. please bisect. reboot recovers.",
  },
  {
    id: "R-037",
    date: "2026-08-09",
    vehicleModel: "Volt Hatch",
    softwareVersion: "4.2.0",
    affectedVehicles: 9,
    source: "Dealer Tech",
    location: "San Jose Store",
    subsystem: "ADAS",
    severity: "P2",
    severityReason: "One model only, small n, camera calibration nag, not described as false braking.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Calibration procedure in service; not remote.",
    triggerCondition: "Specific ECU configuration",
    triggerReason: "Only Volt Hatch windshield camera after a glass replacement batch.",
    suggestedOwner: "Vehicle Software",
    ownerReason: "ADAS calibration config; confirm it is glass-shop related not a campaign.",
    theme: "ADAS Calibration — Volt Hatch Only",
    triageSummary: "Volt-only camera calibration nag after glass work. Limited model scope.",
    rawText:
      "only seen on volt hatch. lane-keep unavailable until camera cal. 9 cars, all after windshields. not the ridge. tech did cal, good. one model so far. not spreading to helix.",
  },
  {
    id: "R-038",
    date: "2026-08-29",
    vehicleModel: "Multiple (Apex, Ridge, Courier)",
    softwareVersion: "4.2.1",
    affectedVehicles: 76,
    source: "Fleet Ops",
    location: "Multi-region",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Same overnight OTA failure spanning models — campaign-level, not a single nameplate.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Depots still flashing mixed models.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Cross-model, parked overnight, BCM step.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Multi-model campaign behavior is an OTA platform defect.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Overnight BCM stall confirmed across Apex, Ridge, and Courier. Pause discussion is justified.",
    rawText:
      "affecting multiple vehicle models now. apex, ridge, courier all hanging on BCM after sitting overnight on 4.2.1. 76 additional this week across regions. this is not a van-only wiring thing. please treat as campaign.",
  },
  {
    id: "R-039",
    date: "2026-08-30",
    vehicleModel: "Apex Van",
    softwareVersion: "4.2.1",
    affectedVehicles: 91,
    source: "OEM Support",
    location: "Mexico City Hub",
    subsystem: "OTA Update",
    severity: "P1",
    severityReason: "Another large depot, same defect, different vocabulary — still campaign-blocking.",
    recoveryPath: "Technician / Service Visit",
    recoveryReason: "Local term is 'module programming in service' — same as reflash.",
    triggerCondition: "Vehicle parked overnight before OTA campaign",
    triggerReason: "Units 'cold-soaked on the lot' then failed the body controller package.",
    suggestedOwner: "OTA Platform",
    ownerReason: "Same sleep/resume OTA issue, translated through local service language.",
    theme: "OTA Updates Failing After Vehicle Sleep",
    triageSummary: "Duplicate of the overnight OTA stall using different terminology (cold-soak, module programming).",
    rawText:
      "body controller package does not resume after a cold soak on the lot. morning programming session dies near two-thirds complete. service had to do module programming on 91 apex. overnight unused vehicles only. we are calling it a sleep-state campaign defect not a 'failed flash' in the old sense.",
  },
  {
    id: "R-040",
    date: "2026-08-28",
    vehicleModel: "Helix Sedan",
    softwareVersion: "4.1.8",
    affectedVehicles: 1840,
    source: "Customer Care",
    location: "Global retail",
    subsystem: "Infotainment",
    severity: "P3",
    severityReason: "Cosmetic/audio hiss, no function loss — but volume is enormous so Themes must surface it.",
    recoveryPath: "OTA / Remote Recovery",
    recoveryReason: "No service required; possible EQ/software tweak later.",
    triggerCondition: "Specific software version",
    triggerReason: "Common on 4.1.8 Helix; low individual severity.",
    suggestedOwner: "Infotainment",
    ownerReason: "Audio pipeline / DSP.",
    theme: "High-Volume Low-Severity Audio Hiss",
    triageSummary: "Faint hiss after Bluetooth pause on ~1800 Helix. P3 each, high Theme rank because of count.",
    rawText:
      "minor inconvenience — faint hiss when bluetooth is paused. isolated? no, care has 1840 helix tickets in 4.1.8. nobody is stranded. they live with it. still, NPS mentions it constantly. would be useful if we EQ'd it out. not a crash, not a freeze.",
  },
];

// Re-exported from rubric.js so the weights and labels have exactly one definition.
// Kept here because existing modules already import them from seed.js.
export { SEVERITY_WEIGHTS, SEVERITY_LABELS } from "./rubric.js";
